#!/bin/zsh
## Custom command `git web`
# Opens your default browser directly to
# your current branch and position in github or gitlab

if git status &>/dev/null; then
    origin=$(git remote get-url --push origin)

    sub_github="github"
    sub_gitlab="gitlab"

    if [[ "$origin" == *"$sub_github"* ]]; then
        git_base="https://github.com"
        git_path=${${origin/git@github.com:/}/.git/}
    elif [[ "$origin" == *"$sub_gitlab"* ]]; then
        git_base="https://gitlab.com"
        git_path=${${origin/git@gitlab.com:/}/.git}
    else
        echo "Unknown git domain..."
        exit 1
    fi
    
    git_repo_url="${git_base}/${git_path}"

    git_branch=$(git branch --show-current)

    git_pwd=$(git rev-parse --show-prefix)

    git_url="${git_repo_url}/tree/${git_branch}/${git_pwd}"

    open "${git_url}"
else
    echo "This isn't a git repository..."
fi