#!/bin/zsh

if git status &>/dev/null; then
    origin=$(git remote get-url --push origin)

    git_base_url="https://github.com/${${origin/git@github.com:/}/.git/}"

    git_branch=$(git branch --show-current)

    pr_url="${git_base_url}/compare/main...${git_branch}"

    open "${pr_url}"
else
    echo "This isn't a git repository..."
fi
