#!/bin/zsh

if git status &>/dev/null; then
    origin=$(git remote get-url --push origin)
    
    git_base_url="https://github.com/${${origin/git@github.com:/}/.git/}"

    git_branch=$(git branch --show-current)

    git_path=$(git rev-parse --show-prefix)

    git_url="${git_base_url}/tree/${git_branch}/${git_path}"

    /Applications/Firefox.app/Contents/MacOS/firefox "${git_url}"
else
    echo "This isn't a git repository..."
fi